version       = "0.1.0"
author        = "Andre von Houck"
description   = "Silky immediate mode UI graphics."
license       = "MIT"

srcDir        = "src"

requires "nim >= 2.2.4"
requires "pixie"
requires "shady#f9ab26d946c32cd9da7c04394a1353a375a9dba5"
requires "vmath"
requires "windy"
requires "dx12"
requires "vk14"
requires "metal4"
requires "chroma"
requires "bumpy"
requires "jsony"
requires "fluffy"
